# Dev Containerではこちらが優先される。
services:
  python-environment:
    build:
      target: devcontainer
      context: .
      dockerfile: Dockerfile
    image: python-devcontainer:latest
    container_name: python-container-devcontainer
    volumes:
      - ./:/app # contextから見たパスではなく，リポジトリから見たパスがvolume mountされる。
