name: create release on tag
on:
  release:
    types: [created]

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.12.4
  RELEASE_VERSION: ${{ github.event.release.tag_name }}


jobs:
  create-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # checkout repository to runner
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: install package using aqua
        uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.29.0

      - name: set up python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: run buildd
        run: |
          rye pin ${{ env.PYTHON_VERSION }}
          rye sync
          rye build

      # NOTE: matrix内でenv.hogehogeのように展開できないので愚直に2回アップロードをする。
      - name: upload Releases whl
        uses: shogo82148/actions-upload-release-asset@8f032eff0255912cc9c8455797fd6d72f25c7ab7 # v1.7.5
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./dist/my_portscanner-${{ env.RELEASE_VERSION }}-py3-none-any.whl"
          asset_name: "./dist/my_portscanner-${{ env.RELEASE_VERSION }}-py3-none-any.whl"
      - name: upload Releases tar.gz
        uses: shogo82148/actions-upload-release-asset@8f032eff0255912cc9c8455797fd6d72f25c7ab7 # v1.7.5
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./dist/my_portscanner-${{ env.RELEASE_VERSION }}.tar.gz"
          asset_name: "./dist/my_portscanner-${{ env.RELEASE_VERSION }}.tar.gz"
